services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: identity-user      
      MYSQL_USER: user              
      MYSQL_PASSWORD: 123456     
    ports:
      - "3308:3306"  
    volumes:
      - D:\docker\volume\mysql-data\identity:/var/lib/mysql  
    networks:
      - shopapp

volumes:
  mysql-data:

networks:
  shopapp:
    driver: bridge
