version: '3.8'

services:
  zipkin:
    container_name: zipkin_container
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

#volumes:
#  postgres:
#  pgadmin:
